language: csharp
solution: src/Selenium.Essentials/Selenium.Essentials.sln
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test test/Selenium.Essentials.UnitTests/Selenium.Essentials.UnitTests.csproj
