language: csharp
solution: ./src/Selenium.Essentials/Selenium.Essentials.sln
mono: none
dotnet: 2.1.502

install:
  - nuget restore ./src/Selenium.Essentials/Selenium.Essentials.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner

script:
 - dotnet build
 - dotnet test test/Selenium.Essentials.UnitTests/Selenium.Essentials.UnitTests.csproj
